name: "🐛 Bug Report"
description: Found something you weren't expecting? Report it here!
title: "🐛 Bug: <title>"
labels: [
    "Type ◦ Bug"
]
body:
    - type: markdown
      attributes:
          value: |
              1.  Please speak `English`.
              2.  Make sure you are using the latest version and take a moment to check that your issue hasn't been reported before.
              3.  It's really important to provide pertinent details and logs, incomplete details will be handled as an invalid report.
              4.  Before creating this bug report, ensure you updated your applications to the latest versions.
                  Check your `csf.conf` to ensure there are no typos or errors.
              5.  To get detailed logs of the issue, open:
                    `/var/log/lfd.log`

              <br />

  - type: textarea
    id: description
    attributes:
        label: Description
        description: |
            Please provide a description of your issue here.
    validations:
        required: true
